### ISSUE TITLE
examples in the repo not working after initial install

### ISSUE THREAD

**Issue by gunstonej** [ooreilly/mydocstring#6]
Hi there, 

i installed mydocstring as described in the readme: 

`pip install mydocstring`

when i run the example.sh script from within the appropriate conda env i get the following error:

`  File "C:\ProgramData\Miniconda3\envs\mf_main\Scripts\mydocstring.exe\__main__.py", line 7, in <module>
  File "c:\programdata\miniconda3\envs\mf_main\lib\site-packages\mydocstring\docstring.py", line 39, in main
    cmd = command.Command(options)
  File "c:\programdata\miniconda3\envs\mf_main\lib\site-packages\mydocstring\command.py", line 53, in __init__
    returns=self.docstring['return_type'])
KeyError: 'return_type'
Traceback (most recent call last):
  File "c:\programdata\miniconda3\envs\mf_main\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\envs\mf_main\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\envs\mf_main\Scripts\mydocstring.exe\__main__.py", line 7, in <module>
  File "c:\programdata\miniconda3\envs\mf_main\lib\site-packages\mydocstring\docstring.py", line 39, in main
    cmd = command.Command(options)
  File "c:\programdata\miniconda3\envs\mf_main\lib\site-packages\mydocstring\command.py", line 53, in __init__
    returns=self.docstring['return_type'])
KeyError: 'return_type'
bash: pause: command not found
Microsoft Windows [Version 10.0.18362.476]
(c) 2019 Microsoft Corporation. All rights reserved.
`

any suggestions would be most welcome?

**Comment by ooreilly** [comment]
Hi @gunstonej ,

Thanks for bringing this issue to my attention. Turns out that the examples were broken in the version you are using. I just released an updated version (0.2.4). Can you please try that one and let me know if it fixes the problem for you?

**Comment by gunstonej** [comment]
thanks for your quick response and apologies for my slow reply!

pulled your update and ran again:
```
(mf_main) C:\engDev\git_extrnl\mydocstring-master\mydocstring-master\examples>python mydocstring example.py example_function --markdown
python: can't open file 'mydocstring': [Errno 2] No such file or directory

(mf_main) C:\engDev\git_extrnl\mydocstring-master\mydocstring-master\examples>mydocstring example.py example_function --markdown
Traceback (most recent call last):
  File "c:\programdata\miniconda3\envs\mf_main\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\envs\mf_main\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\envs\mf_main\Scripts\mydocstring.exe\__main__.py", line 7, in <module>
  File "c:\programdata\miniconda3\envs\mf_main\lib\site-packages\mydocstring\docstring.py", line 39, in main
    cmd = command.Command(options)
  File "c:\programdata\miniconda3\envs\mf_main\lib\site-packages\mydocstring\command.py", line 53, in __init__
    returns=self.docstring['return_type'])
KeyError: 'return_type'
```

when i run the examples.sh script the output json, md and txt files are all written blank... 

thanks

**Comment by ooreilly** [comment]
@gunstonej  are you sure you are using the most recent version? The error you are getting looks the same as before.

Try 
```
mydocstring --version
```
it should print: `0.2.4`.

**Comment by gunstonej** [comment]
apologies, you're absolutely right. 
i didn't force the upgrade. 
did this:
`pip install mydocstring --upgrade`
and it is now working. 
many thanks
